e.g if USER is DENNIS

KEVIN01	    android knitting app	        DENNIS
LINDA01	    xml compression tool	        GRACE
MARY01	    concurrency visualisation tool	ADA
NEIL01	    chess move analyser	            DENNIS
OSCAR01	    deep web query optimizer	    BJARNE
PREETI01	social web mining tool	        LARRY
QUINCY01	kitchen design app	            GRACE

if USER is QUINCY01 

QUINCY01	kitchen design app	            GRACE
